# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Computer Applications Primer
email: eric.kuha@lltc.edu
description: >- 
    A Computer Applications textbook for use by students at Leech Lake Tribal College. Or anyone else, for that matter.
baseurl: "" 
url: "https://itech.erickuha.com" 
github_username: SirYancy

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme


remote_theme: pmarsceill/just-the-docs 

color_scheme: "dark"

search_enabled: true

footer_content: "Copyright &copy; 2015-2020 Eric Kuha. Distributed by an <a href=\"https://github.com/SirYancy/computer-apps/tree/master/LICENSE\">MIT license.</a>"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
